# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.cache/wt} [current_project]
set_property parent.project_path {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/mpg.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/ControlUnit.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/DivizorFrecventa_SD.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/SDinitialise.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/SDController.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/ImageCounter.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/RAM.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/ModulMicroSD.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/VgaPackage.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/fsm_horizontal_sync.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/fsm_vertical_sync.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/sync_generator.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/DivizorFrecventa_25.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/Memory_address.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/ControllerVGA.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/Offset_counter.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/Effect_generator.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/ExecutionUnit.vhd}
  {/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/sources_1/new/BlackBox.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/constrs_1/imports/SSC/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{/home/birlutiuclaudiu/Facultate/An3_sem1/SSC/PROJECT/PROIECT FINAL/BirlutiuClaudiu_VGA/BirlutiuClaudiu_VGA.srcs/constrs_1/imports/SSC/Nexys4DDR_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top BlackBox -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef BlackBox.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file BlackBox_utilization_synth.rpt -pb BlackBox_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
